sudo: required
services:
  - docker

#build dev app image on Travis 
before_install:
  - docker build -t doob/docker-react-1 -f dockerfile.dev .

#do a test
script:
  - docker run doob/docker-react-1 npm run test -- --coverage