sudo: required
services:
  - docker

#build dev app image on Travis 
before_install:
  - docker build -t pv/react_docker_1 -f dockerfile.dev

#do a test
script:
  - docker run pv/react_docker_1 npm run test -- --coverage