sudo: required
services:
  - docker

#build dev app image on Travis 
before_install:
  - docker build -t pv/react-docker -f dockerfile.dev .

#do a test
script:
  - docker run pv/react_docker npm run test -- --coverage