FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm config set unsafe-perm true
RUN npm install --force

#keep this in case not using docker-compose to do volume ref
COPY . .

RUN chown -R node /app/node_modules
USER node

CMD ["npm","run","start"]